import {defaults,renderHomepage,escapeHTML} from './template.js';
const form=document.querySelector('#settings');
const frame=document.querySelector('#preview');
const state=structuredClone(defaults);
let currentHTML='',toastTimer,photoGeneration=0;
document.querySelector('#news-fields').innerHTML=defaults.news.map((n,i)=>`<fieldset class="news-set"><legend>お知らせ 0${i+1}</legend><label class="field">見出し<input name="newsTitle${i}" maxlength="80" value="${escapeHTML(n.title)}"></label><label class="field">本文<textarea name="newsBody${i}" rows="5" maxlength="3000">${escapeHTML(n.body)}</textarea></label></fieldset>`).join('');
function notify(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.hidden=true,4500);}
function updatePhoto(){const thumb=document.querySelector('#photo-thumb');thumb.replaceChildren();if(state.photo){const img=new Image();img.src=state.photo;img.alt='現在のプロフィール画像';thumb.append(img);}else{thumb.textContent='画像なし';}document.querySelector('#remove-photo').disabled=!state.photo;}
function render(){currentHTML=renderHomepage(state);frame.srcdoc=currentHTML.replace('<head>', '<head><base href="about:srcdoc">');document.querySelector('#file-size').textContent=`HTML ${(new Blob([currentHTML]).size/1024).toFixed(1)} KB`;}
function readForm(){const f=new FormData(form);for(const k of ['name','english','profile','intro','linkLabel','linkUrl','updated','background','navColor','watermark'])state[k]=String(f.get(k)??'');state.showWatermark=f.has('showWatermark');state.news=defaults.news.map((_,i)=>({title:String(f.get(`newsTitle${i}`)??''),body:String(f.get(`newsBody${i}`)??'')}));render();}
let renderTimer;form.addEventListener('input',()=>{clearTimeout(renderTimer);renderTimer=setTimeout(readForm,80);});form.addEventListener('submit',e=>e.preventDefault());
function selectTab(name){document.querySelectorAll('[role=tab]').forEach(tab=>{const selected=tab.dataset.tab===name;tab.setAttribute('aria-selected',selected);tab.tabIndex=selected?0:-1;document.querySelector(`#panel-${tab.dataset.tab}`).hidden=!selected;});}
document.querySelectorAll('[role=tab]').forEach((tab,i,tabs)=>{tab.addEventListener('click',()=>selectTab(tab.dataset.tab));tab.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();selectTab(tabs[next].dataset.tab);});});
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',b===button);});document.querySelector('#browser-window').classList.toggle('mobile',button.dataset.view==='mobile');}));
function saveHTML(){readForm();const url=URL.createObjectURL(new Blob([currentHTML],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${(state.name||'my').replace(/[<>:"/\\|?*\u0000-\u001f]/g,'').slice(0,40)||'my'}-homepage.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);notify('ホームページのHTMLを保存しました。');}
document.querySelectorAll('.download').forEach(b=>b.addEventListener('click',saveHTML));
document.querySelector('#open-preview').addEventListener('click',()=>{readForm();const url=URL.createObjectURL(new Blob([currentHTML],{type:'text/html;charset=utf-8'}));window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000);});
const resetDialog=document.querySelector('#reset-dialog');document.querySelector('#reset').addEventListener('click',()=>resetDialog.showModal());document.querySelector('#cancel-reset').addEventListener('click',()=>resetDialog.close());document.querySelector('#confirm-reset').addEventListener('click',()=>{photoGeneration++;Object.assign(state,structuredClone(defaults));form.reset();document.querySelector('#photo').value='';selectTab('profile');updatePhoto();render();resetDialog.close();notify('最初の作例に戻しました。');});
document.querySelector('#remove-photo').addEventListener('click',()=>{photoGeneration++;state.photo='';state.generatedPortrait=false;document.querySelector('#photo').value='';updatePhoto();render();});
document.querySelector('#photo').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;const generation=++photoGeneration;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){notify('JPG・PNG・WebPの画像を選んでください。');e.target.value='';return;}if(file.size>2*1024*1024){notify('2MB以下の画像を選んでください。');e.target.value='';return;}try{const source=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const image=new Image();image.src=source;await image.decode();if(generation!==photoGeneration)return;state.photo=source;state.generatedPortrait=false;updatePhoto();render();notify('プロフィール画像を変更しました。');}catch{notify('画像を読み込めませんでした。別の画像をお試しください。');e.target.value='';}});
updatePhoto();render();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'get_homepage_settings',description:'編集中のホームページ設定を読み取ります。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){readForm();const {photo,...settings}=state;return {settings,hasPhoto:!!photo};}});register({name:'update_homepage_profile',description:'名前・プロフィール・ひとことを編集し、表示中のプレビューに反映します。公開サイトへの保存やダウンロードは行いません。',inputSchema:{type:'object',properties:{name:{type:'string',maxLength:50},english:{type:'string',maxLength:80},profile:{type:'string',maxLength:2000},intro:{type:'string',maxLength:500}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('設定オブジェクトが必要です。');const limits={name:50,english:80,profile:2000,intro:500};for(const [key,value] of Object.entries(input)){if(!(key in limits)||typeof value!=='string'||value.length>limits[key])throw new Error('設定のキー・値・長さが不正です。');}for(const [key,value] of Object.entries(input))form.elements.namedItem(key).value=value;readForm();return {name:state.name,english:state.english,profile:state.profile,intro:state.intro};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
